### ISSUE TITLE
Couldn`t write changelog: check the file path

### ISSUE THREAD

**Issue by dy-sh** [badrbouslikhin/obsidian-vault-changelog#6]
Error message: Couldn`t write changelog: check the file path

Tried different file paths, nothing helps.

**Comment by patowod** [comment]
Love the idea! Unfortunately I encounter the same message as @derwish-pro. I'm on Mac OS Catalina and I have my vault within the iCloud. This works fine for everything. I programatically tested the following path and probably most derivations:

```
/Users/User/Library/Mobile Documents/26N4YFUEA42~pro~writer/Documents/changelog.md
```

Any ideas appreciated.

**Comment by Priyank-Vaghela** [comment]
I faced the same issue. Here's a quick solution:

1. Create a new file, for example - `Misc/changelog`.
2. Go to **Settings -> Plugin Option -> Vault Changelog**
2. Enter path in **Changelog note location - Misc/changelog.md**
3. Restart Obsidian.md

**Notes:**
> - Make sure to keep a **_proper file path and a name_**, like the one I have used.
> - If you are creating a new file with Obsidian then **_don't put a (.md) extension_**.

**Comment by patowod** [comment]
Thanks a lot for your comment @Priyank-Vaghela. I gave it another go and I found that restarting Obsidian was key to my setup / issue. So, having my "changelog.md" in my notes root the "changelog.md" is the only part that is needed in the plugin settings. Key is then to **restart Obsidian**. Now it works like a charm!

**Comment by MrZeroo00** [comment]
I cannot reproduce this issue. Glad you found a workaround.
@Priyank-Vaghela I see that you forked the repo, any idea what's going on here?

**Comment by Priyank-Vaghela** [comment]
> I cannot reproduce this issue. Glad you found a workaround.
> @Priyank-Vaghela I see that you forked the repo, any idea what's going on here?

Hi @MrZeroo00, I faced few issues while setting up the plugin with Obsidian. However, the solution was quite simple; therefore, I thought of updating the documentation by forking and then requesting a PR merge. Thank you. I hope you are doing well.

**Comment by derwish-pro** [comment]
> I faced the same issue. Here's a quick solution for #6:
> 
> 1. Create a new file, for example - `Misc/changelog`
> 2. Go to **Settings -> Plugin Option -> Vault Changelog**
> 3. Enter path in **Changelog note location - Misc/changelog.md**
> 4. Restart Obsidian
> 
> **Notes:**
> 
> > * Make sure to keep a **_proper file path and a name_**, like the one I have used.
> > * If you are creating a new file with Obsidian, then **_don't put a (.md) extension_**.

It works for me. Thank you.

**Comment by derwish-pro** [comment]
> Are you using an absolute file path?
> Could you share a screenshot of your vault file tree and the path you're setting?

I tried to use relative path (filename without folders).
My vault path: C:\Users\Derwish\Documents\MY NOTES\obsidian-notes

**Comment by jorgb** [comment]
This does not work. It only works in the root folder.
File: Changelog.md
Config: Changelog.mg

All works fine. It gets updated.

File: 000 Home\Changelog.md
Config: 000 Home\Changelog.md

Can't update file.
Restarted obsidian, still can't update file. I suspect the whitespace in the path, or something else, but I really do not want this file in my vault root, so for now it is disabled. Will check updates in the future and hope it gets resolved.

**Comment by osaze-nosaze** [comment]
Hi, everyone.
The Vault Changelog plugin sounds very useful to me. I thank the maker. However, I cannot get it to work, no matter what I try. The issue is the one under discussion here: "Could not write the changelog. Check the file path." I have followed the instructions on how to solve it but every effort has failed so far.

I use a Linux system and the absolute path to my notes is: /media/imose/Repository/Notes. I have the changelog.md file in the Notes folder; so for "Changelog note location" in the plugin settings, I put in: /media/imose/Repository/Notes/changelog.md. I restarted Obsidian after this, waited about half a minute and restarted it. The plugin gave me the error message. 

I have re-tried this process numerous times, after changing one element or another, but I get the same result every time. For instance, I have removed the / before "media" in the filepath, removed everything before "Repository" in the path, and even used only "Notes/changelog.md" -- as I understood derwish-pros' solution above to mean-- hoping it would work since the changelog file is in the vault root. Nothing has worked. I am sure I am doing something wrong or missing something.

I would appreciate anyone's help, preferably in language fit for computer dummies like me.

Thanks in advance

**Comment by ramification** [comment]
> then **_don't put a (.md) extension_**.

NOW I understand why it wasn't working ! Thank you !

**Comment by badrbouslikhin** [comment]
I've created a new branch that should address the onboarding experience issue (#13).

If you encounter any problems, please feel free to reopen this issue and provide additional details.

**Comment by FetchFast** [comment]
Thanks for the workaround of making a file for the plugin because it can't do it itself. I hope this function can be introduced in a new version

**Comment by merlinuwe** [comment]
It looks like there follows a wrong exentsion suggestion in the first input field:

![image](https://github.com/badrbouslikhin/obsidian-vault-changelog/assets/4138869/86acd357-43ed-4633-b7c2-775ba04d49ce)

This confused me.

For me, this is correct:

Meta/Allgemeines/changelog_Uwe-PC-SSD

![image](https://github.com/badrbouslikhin/obsidian-vault-changelog/assets/4138869/985796c5-2172-47a6-b15e-53e27c3f98b2)

Perhaps it makes sense to make the field a little wider so that the (correct[ed]) content is easier to read.
